name: ca6
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.5
  http: ^1.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_fonts: ^6.1.0
  firebase_database: ^10.2.7
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/